version: "2"
services:
  application:
    image: ${IMAGE_NAME}
    container_name: airflow
    ports:
      - "8080:8080"
    environment:
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_DEFAULT_REGION=${AWS_DEFAULT_REGION}
    volumes:
      - "./census_consumer_complaint_data:/census_consumer_complaint_data"
  
  prediction:
    image: tensorflow/serving:latest
    ports:
      - "8501:8501"
      - "8500:8500"
    volumes:
      - "./census_consumer_complaint_data/saved_models:/avnish/saved_models"
    environment:
      - "MODEL_NAME=saved_models"
      - "MODEL_BASE_PATH=/avnish"